"use client";
import { useState } from "react";
import { useSession } from "next-auth/react";
import { LoaderCircle, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";

export function DeleteCustomerModal({ customerId, customerName, open, onOpenChange, onDeleted }: { customerId: string | null; customerName?: string; open: boolean; onOpenChange: (open: boolean) => void; onDeleted: () => void }) {
  const { data: session } = useSession(); const [isDeleting, setIsDeleting] = useState(false); const [error, setError] = useState("");
  const remove = async () => { if (!customerId || isDeleting) return; const token = session?.user.accessToken; if (!token) { setError("Your session is missing. Please sign in again."); return; } setIsDeleting(true); setError(""); try { const response = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_API_URL}/contacts/${encodeURIComponent(customerId)}`, { method: "DELETE", headers: { Authorization: `Bearer ${token}` } }); const result = (await response.json().catch(() => ({}))) as { success?: boolean; message?: string }; if (!response.ok || result.success === false) throw new Error(result.message || "Unable to delete customer."); toast.success("Customer deleted successfully."); onOpenChange(false); onDeleted(); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Unable to delete customer."); } finally { setIsDeleting(false); } };
  return <Dialog open={open} onOpenChange={(next) => !isDeleting && onOpenChange(next)}><DialogContent overlayClassName="bg-[#0E1224]/40 backdrop-blur-[4px]" className="w-[calc(100%-24px)] max-w-[420px] gap-0 !rounded-[16px] border-0 bg-white p-6 text-center shadow-[0_24px_80px_rgba(14,18,36,0.24)]"><span className="mx-auto flex size-12 items-center justify-center rounded-full bg-[#EF4444]/10 text-[#EF4444]"><Trash2 className="size-5" /></span><DialogTitle className="mt-4 text-xl font-semibold text-[#0E1224]">Delete Customer?</DialogTitle><DialogDescription className="mt-2 text-sm leading-6 text-[#73809B]">Are you sure you want to delete <strong className="text-[#343A52]">{customerName || "this customer"}</strong>? This action cannot be undone.</DialogDescription>{error && <p className="mt-3 text-sm text-[#C24152]">{error}</p>}<div className="mt-6 grid grid-cols-2 gap-3"><button type="button" onClick={() => onOpenChange(false)} disabled={isDeleting} className="h-11 rounded-lg border border-[#DCE1EA] text-sm font-medium text-[#596079]">Cancel</button><button type="button" onClick={() => void remove()} disabled={isDeleting} className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#EF4444] text-sm font-medium text-white disabled:opacity-60">{isDeleting && <LoaderCircle className="size-4 animate-spin" />}{isDeleting ? "Deleting..." : "Delete"}</button></div></DialogContent></Dialog>;
}
