import { CheckSquare } from "lucide-react";
import type { CalendarDashboard } from "./types";

const metric=(entry:{availability:string;value:number|null})=>entry.availability==="AVAILABLE"&&entry.value!==null?entry.value:"Unavailable";
export function PriorityAutomation({priority,automation}:{priority:CalendarDashboard["priority"];automation:CalendarDashboard["automation"]}) {
 const total=priority.counts.high+priority.counts.medium+priority.counts.low; const percent=(n:number)=>total?Math.round(n/total*100):0;
 const averageScore = priority.averageScore.value ?? 0;
 const rows=[["Notes Generated",automation.notesGenerated],["Action Items Created",automation.actionItemsCreated],["Tasks Assigned",automation.tasksAssigned],["Follow-up Emails Sent",metric(automation.followUpEmailsSent)],["CRM Records Updated",metric(automation.crmRecordsUpdated)],["Customer Health Updated",metric(automation.customerHealthUpdated)]];
 return <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-[12px] bg-white p-6"><h2 className="border-b border-[#E4EAF8] pb-4 text-xl font-medium">Priority Score</h2><h3 className="mt-4 text-base font-medium">Meetings by Priority</h3><div className="mt-3 flex flex-col items-center gap-4 sm:flex-row sm:justify-between"><div className="flex size-[120px] shrink-0 items-center justify-center rounded-full bg-[conic-gradient(#EF4444_0_33%,#F59E0B_33%_66%,#10B981_66%)]"><div className="flex size-[72px] flex-col items-center justify-center rounded-full bg-white"><strong className="text-base font-medium">{averageScore}</strong><span className="text-[10px]">Avg Score</span></div></div><div className="space-y-3 text-xs"><p><i className="mr-1 inline-block size-2 rounded-full bg-[#EF4444]"/>High ({priority.counts.high}) {percent(priority.counts.high)}%</p><p><i className="mr-1 inline-block size-2 rounded-full bg-[#F59E0B]"/>Medium ({priority.counts.medium}) {percent(priority.counts.medium)}%</p><p><i className="mr-1 inline-block size-2 rounded-full bg-[#10B981]"/>Low ({priority.counts.low}) {percent(priority.counts.low)}%</p><p className="text-[#8B93B8]">Unclassified: {priority.unclassified}</p></div></div><div className="mt-4 border-t border-[#E4EAF8] pt-4"><h3 className="mb-2 text-base font-medium">Confidence Score</h3>{priority.confidenceScores.items.length===0?<p className="rounded-[8px] bg-[#F5F7FF] p-4 text-sm text-[#8B93B8]">Confidence scores are currently unavailable.</p>:<div className="space-y-2">{priority.confidenceScores.items.map((item,i)=><div key={item.meetingId||i} className="flex h-[39px] items-center gap-2 rounded-[8px] bg-[#F5F7FF] pr-2 text-sm"><span className="h-full w-1 rounded-[2px] bg-[#10B981]"/><span className="flex-1 truncate">{item.title||`Meeting ${i+1}`}</span><span>{item.score}</span><span>{item.priority}</span></div>)}</div>}</div></article><article className="rounded-[16px] bg-white p-6"><h2 className="border-b border-[#F5F7FF] pb-4 text-xl font-medium">Next - Meeting Automation</h2><div className="mt-4 space-y-2">{rows.map(([label,value])=><div key={label} className="flex min-h-[37px] items-center gap-2 rounded-[8px] bg-[#F5F7FF] pr-2 text-sm"><span className="self-stretch w-1 rounded-[2px] bg-[#10B981]"/><CheckSquare className="size-5 text-[#10B981]"/><span className="flex-1 py-2">{label}</span><strong className="font-medium">{value}</strong></div>)}</div></article></section>;
}
